/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javagui */

#ifndef _Included_javagui
#define _Included_javagui
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javagui
 * Method:    pension
 * Signature: (IIII[D)D
 */
JNIEXPORT jdouble JNICALL Java_javagui_pension
  (JNIEnv *, jobject, jint, jint, jint, jint, jdoubleArray);

/*
 * Class:     javagui
 * Method:    calculatePension
 * Signature: (IIFI[F[F[FIFF)D
 */
JNIEXPORT jdouble JNICALL Java_javagui_calculatePension
  (JNIEnv *, jobject, jint, jint, jfloat, jint, jfloatArray, jfloatArray, jfloatArray, jint, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
